### ISSUE TITLE
i have a issue 

### ISSUE THREAD

**Issue by UjjawalPratap1** [UofT-Box/UofT-Timetable-Builder#45]
Can you tell me what you mean by "target file" in the readme clone instruction in the window, please?

**Comment by Zhengyu-Joey-Wang** [comment]
Hello, thank you very much for submitting the issue.

After reviewing the readme file, I found that indeed there are some areas where the descriptions are unclear. This is mainly because we had a major update in March, but the readme was not updated accordingly, leading to outdated information. I apologize for this oversight.

I have now updated the readme, and I believe the instructions are now clear and accurate.

If you have any more questions or need further assistance, please feel free to ask.
